Add slack-alerts package
Kava-Labs/go-tools pull request #38
Opened 2021-08-18 16:18 UTC by drklee3

2021-08-24 15:12 UTC, denalimarsh requested changes
Great work! I'm impressed with how quickly you've picked up Go essentials in this initial implementation. In this initial review, I have some recommendations and potential optimizations you should consider. I'll take a closer look at the database/server logic in a future second review.

- You could potentially improve the usability and extensibility of your application with [cobra](https://github.com/spf13/cobra), this will allow the app to be run with sub-commands. For example, we could combine `slack-alerts` and `auction-alerts` into a new root folder `alerts` where `slack-alerts` is a reusable client that `auction-alerts` and other alerting services can use. In this way, we could add future alerting services and manage them all under an `alerts` cmd i.e. `alerts actions run` and `alerts swaps run`
- Consider a hierarchical file structure as seen in the `claimer` service.
- Add a Makefile so your app can be installed with cmd `make install`

If you haven't already, download the following extensions in VSCode:
- Go Team at Google: Rich Go language support for Visual Studio Code
- Code Spell Checker: Spelling checker for source code
- TODO Highlight: highlight TODOs, FIXMEs, and any keywords, annotations
- Paste JSON as Code: Copy JSON, paste as Go, TypeScript, C#, C++ and more

2021-08-24 15:12 UTC, denalimarsh commented on auction-alerts/main.go
> +func main() {
Generally `main.go` should have as little code as possible, calling out to an executable cmd that contains high-level logic. See the spammer service's [main.go](https://github.com/Kava-Labs/go-tools/blob/master/spammer/main.go) for an example.

2021-08-24 15:12 UTC, denalimarsh commented on slack-alerts/go.mod
> +go 1.16
The two modules have different Go versions. Not a problem, but a little strange as this chunk of work is being submitted together. If you don't have a specific reason for the difference, I recommend standardizing on one or the other.

2021-08-24 15:12 UTC, denalimarsh commented on slack-alerts/client.go
> +type SlackAlerter struct {
+1 for introducing reusable component `SlackAlerter`. Good separation of concerns, but I'm not convinced yet that it needs its own go module.

2021-08-24 23:30 UTC, drklee3 commented on auction-alerts/client.go
> +	for {
Are we assuming either that:
1. There is always less than 1000 auctions, or 
2. 1000 auctions would be enough to trigger alerts such that we don't need any more than 1000?

This `GetAuctions` func I copied from the `auctions-bot` so I'm not 100% sure if I'm understanding this, the linked function, and the cosmos `client.Paginage` function correctly, but without the loop it would be just fetching at most 1000 right?

2021-08-25 15:17 UTC, denalimarsh approved these changes
Refactor looks good!

2021-08-25 15:17 UTC, denalimarsh commented on auction-alerts/client.go
> +	for {
Ah, I see now. I didn't realize this was already used in production on another service. I checked it out and I think it's functionally correct.

2021-08-25 15:17 UTC, denalimarsh commented on auction-alerts/client.go
> +	for {
Ignore what I said above. Results are returned from the querier in chunks of pages, where the limit determines how many items are on the page. We can keep the for-loop and the defaults.

2021-08-25 15:52 UTC, merged