Upgrade auctions bot
Kava-Labs/go-tools pull request #44
Opened 2021-12-28 21:18 UTC by drklee3

Upgrades auction bot to v0.44 and uses grpc for queries and txs.

2021-12-30 15:20 UTC, nddeluca commented on auction-bot/grpc_client.go
> +	if enableTls {
We could include the scheme in the `target`, then choose secure/insecure based on that - example at https://github.com/Kava-Labs/go-tools/blob/master/hard-keeper-bot/main.go#L40.

Does require passing the entire `https://grpc.testnet.kava.io:443` string, but doesn't require a separate parameter

2021-12-30 15:24 UTC, nddeluca requested changes
lgtm, I believe the only change that needs to be made is paginating through all auctions

2021-12-30 15:24 UTC, nddeluca commented on auction-bot/data.go
> +	auctionsRes, err := client.Auction.Auctions(ctxAtHeight(latestHeight), &auctiontypes.QueryAuctionsRequest{})
I believe we still need to paginate through all auctions here

2022-01-03 16:58 UTC, karzak approved these changes
LGTM - tested against incentivized testnet and was working properly

2022-01-03 17:51 UTC, nddeluca approved these changes

2022-01-03 17:51 UTC, merged