Update Signer
Kava-Labs/go-tools pull request #67
Opened 2024-07-17 19:32 UTC by sesheffield

add readme, remove kava/app dependency, fix memory leaks and channels, refactors

Ran `testing/main.go` before some refactoring, producing 1000 messages sent and 1000 transactions.
Reran `testing/main.go` afte refactoring, producing 1000 messages sent and 1000 transactions.

2024-07-18 16:26 UTC, karzak reviewed
Great work, thanks for the much needed cleanups and improvements!

2024-07-18 16:26 UTC, karzak commented on signing/README.md
> +## Broadcast Loop Logic:
Can we add a section on running the tests? It looks like `go test ./...` isn't the expected workflow, so good to document the exact steps (ie run a local chain with kvtool, `go run .` from the testing folder).

2024-07-24 20:11 UTC, karzak approved these changes
LGTM

2024-07-25 18:33 UTC, pirtleshell requested changes
awesome job improving the signer's documentation and logging 🏆 

i would love if you could pull those changes into a separate PR so we can discuss the functional (and breaking) changes in the signer method signatures & how shutdowns are handled, and include them separately.

i have more to say about the support of shutdowns / cancellation with the use of `ctx.Done()` than my comments here. 

my current feedback is that you are doing too much in this PR, especially considering it has implications in two of our production services, which will require deployments post-merge. the more we change (however improved or more idiomatic), the more things can go wrong, so we need to consider the tradeoff. please break this pr up into smaller changesets.

2024-07-25 18:33 UTC, pirtleshell commented on signing/testing/main.go
> +	select {}
lol, nice catch

2024-07-25 18:33 UTC, pirtleshell commented on signing/encoding-config.go
> +package signing
hyphens should be avoided in the filename here. prefer either `encodingconfig`, `encoding_config`, or just `encoding`

but question: what is the motivation behind this adapter? it seems unused besides being a passthrough for the sdk codec. i'd omit it and avoid the added complexity

2024-07-25 18:33 UTC, pirtleshell commented on signing/signer.go
> +}
not sure these methods make the code easier or harder to read. personally, i prefer to not have to jump to another method signature to know that setting the error just sets a private variable.

2024-07-26 16:34 UTC, sesheffield commented on signing/encoding-config.go
> +package signing
https://app.shortcut.com/kava-labs/story/2510/remove-kava-app-dependency-in-go-tools-signer

2024-07-26 16:55 UTC, closed without merging